language: ruby
cache: bundler
rvm:
  - 2.1.0
env:
  - DB=postgresql
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database infoeducatie_test'
  - psql -c 'create database infoeducatie_test' -U postgres
